IMPORTING THE NECESSARY LIBRARIES

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

READ THE CSV FILE

In [ ]:
titanic = pd.read_csv("/content/tested.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

TO CHECK NULL VALUES

In [ ]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

**DATA CLEANING**

In [ ]:
tit = titanic.drop(labels=["Cabin","Name","Ticket"], axis=1)
tit

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,892,0,3,male,34.5,0,0,7.8292,Q
1,893,1,3,female,47.0,1,0,7.0000,S
2,894,0,2,male,62.0,0,0,9.6875,Q
3,895,0,3,male,27.0,0,0,8.6625,S
4,896,1,3,female,22.0,1,1,12.2875,S
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,male,NaN,0,0,8.0500,S
414,1306,1,1,female,39.0,0,0,108.9000,C
415,1307,0,3,male,38.5,0,0,7.2500,S
416,1308,0,3,male,NaN,0,0,8.0500,S
417,1309,0,3,male,NaN,1,1,22.3583,C

In [ ]:
tit.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
Embarked        0
dtype: int64

In [ ]:
#Fill the null values of 'Age' column with the mean value
tit["Age"].fillna(tit["Age"].mean(),inplace = True)

In [ ]:
tit.isnull().sum()
tit

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,892,0,3,male,34.50000,0,0,7.8292,Q
1,893,1,3,female,47.00000,1,0,7.0000,S
2,894,0,2,male,62.00000,0,0,9.6875,Q
3,895,0,3,male,27.00000,0,0,8.6625,S
4,896,1,3,female,22.00000,1,1,12.2875,S
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,male,30.27259,0,0,8.0500,S
414,1306,1,1,female,39.00000,0,0,108.9000,C
415,1307,0,3,male,38.50000,0,0,7.2500,S
416,1308,0,3,male,30.27259,0,0,8.0500,S
417,1309,0,3,male,30.27259,1,1,22.3583,C

In [ ]:
tit.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           1
Embarked       0
dtype: int64

In [ ]:
tit.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           1
Embarked       0
dtype: int64

In [ ]:
#Replacing the male and female genders as 0 and 1
tit.replace(['male','female'],[0,1],inplace = True)
tit

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,892,0,3,0,34.50000,0,0,7.8292,Q
1,893,1,3,1,47.00000,1,0,7.0000,S
2,894,0,2,0,62.00000,0,0,9.6875,Q
3,895,0,3,0,27.00000,0,0,8.6625,S
4,896,1,3,1,22.00000,1,1,12.2875,S
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,30.27259,0,0,8.0500,S
414,1306,1,1,1,39.00000,0,0,108.9000,C
415,1307,0,3,0,38.50000,0,0,7.2500,S
416,1308,0,3,0,30.27259,0,0,8.0500,S
417,1309,0,3,0,30.27259,1,1,22.3583,C

In [ ]:
#Replacing the Embarked class values with 0,1,2
tit.replace(["Q","S","C"],[0,1,2],inplace = True)
tit

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,892,0,3,0,34.50000,0,0,7.8292,0
1,893,1,3,1,47.00000,1,0,7.0000,1
2,894,0,2,0,62.00000,0,0,9.6875,0
3,895,0,3,0,27.00000,0,0,8.6625,1
4,896,1,3,1,22.00000,1,1,12.2875,1
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,30.27259,0,0,8.0500,1
414,1306,1,1,1,39.00000,0,0,108.9000,2
415,1307,0,3,0,38.50000,0,0,7.2500,1
416,1308,0,3,0,30.27259,0,0,8.0500,1
417,1309,0,3,0,30.27259,1,1,22.3583,2

In [ ]:
#Fill the null values of 'fare' column with the mean value
tit["Fare"].fillna(tit["Fare"].mean(),inplace = True)

In [ ]:
tit.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [ ]:
tit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Sex          418 non-null    int64
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Fare         418 non-null    float64
 8   Embarked     418 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 29.5 KB

SEPARTING DATA FOR TRAINING AND TESTING

In [ ]:
x = tit.iloc[:,1:]

y = tit['Survived']

In [ ]:
x

     Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0           0       3    0  34.50000      0      0    7.8292         0
1           1       3    1  47.00000      1      0    7.0000         1
2           0       2    0  62.00000      0      0    9.6875         0
3           0       3    0  27.00000      0      0    8.6625         1
4           1       3    1  22.00000      1      1   12.2875         1
..        ...     ...  ...       ...    ...    ...       ...       ...
413         0       3    0  30.27259      0      0    8.0500         1
414         1       1    1  39.00000      0      0  108.9000         2
415         0       3    0  38.50000      0      0    7.2500         1
416         0       3    0  30.27259      0      0    8.0500         1
417         0       3    0  30.27259      1      1   22.3583         2

[418 rows x 8 columns]

In [ ]:
y

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [ ]:
x.shape

(418, 8)

In [ ]:
y.shape

(418,)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [ ]:
x_train.shape

(292, 8)

In [ ]:
y_train.shape

(292,)

In [ ]:
x_test.shape

(126, 8)

In [ ]:
y_test.shape

(126,)

LOGISTIC REGRESSION

In [ ]:
model = LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [ ]:
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [ ]:
Confusion_matrix_prediction_train = confusion_matrix(y_train,x_train_prediction)
Confusion_matrix_prediction_train

array([[188,   0],
       [  0, 104]])

In [ ]:
Confusion_matrix_prediction = confusion_matrix(y_test,x_test_prediction)
Confusion_matrix_prediction

array([[78,  0],
       [ 0, 48]])

In [ ]:
print("Logistic Regression: ")
print("Accuracy Score: ", accuracy_score(x_train_prediction,y_train))
print("Classification Report for training set: ")
print(classification_report(y_train, x_train_prediction))

Logistic Regression:
Accuracy Score:  1.0
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       188
           1       1.00      1.00      1.00       104

    accuracy                           1.00       292
   macro avg       1.00      1.00      1.00       292
weighted avg       1.00      1.00      1.00       292

In [ ]:
print("Logistic Regression: ")
print("Accuracy Score: ", accuracy_score(x_test_prediction,y_test))
print("Classification Report: ")
print(classification_report(y_test, x_test_prediction))

Logistic Regression:
Accuracy Score:  1.0
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        78
           1       1.00      1.00      1.00        48

    accuracy                           1.00       126
   macro avg       1.00      1.00      1.00       126
weighted avg       1.00      1.00      1.00       126

In [ ]:
#DECISON TREE CLASSIFICATION
from sklearn.tree import DecisionTreeClassifier
Iris = DecisionTreeClassifier()
Iris_train = Iris.fit(x_train,y_train)
Iris_prediction = Iris.predict(x_test)

In [ ]:
print("The accuracy of the decision tree classifier is :",{accuracy_score(Iris_prediction,y_test)})

The accuracy of the decision tree classifier is : {1.0}

In [ ]:
confusion_matrix_decision_tree = confusion_matrix(Iris_prediction,y_test)
confusion_matrix_decision_tree

array([[78,  0],
       [ 0, 48]])